routes/web.php
<?php

Route::get('/', [
  'uses' => 'FrontEndController@index',
  'as' => 'index'
]);

Route::get('shop', [
    'uses' => 'FrontEndController@store',
    'as' => 'store'
]);

Route::get('product/{slug}', [
    'uses' => 'FrontEndController@productDetails',
    'as' => 'productDetails'
]);

Route::get('/search/results', [

    'uses' => 'FrontEndController@search_results',
    'as' => 'search.results'
]);

Route::get('blog', [
    'uses' => 'FrontEndController@blog',
    'as' => 'blog'
]);

Route::get('post/{slug}', [
    'uses' => 'FrontEndController@singlePost',
    'as' => 'singlePost'
]);

Route::get('contact', [
    'uses' => 'FrontEndController@contact',
    'as' => 'contact'
]);

Route::post('/mail', [

    'uses' => 'FrontEndController@contactStore',
    'as' => 'contact.store'
]);

Route::get('/cart', [

    'uses' => 'ShoppingController@cart',
    'as' => 'cart'
]);

Route::get('/cart/delete/{id}', [

    'uses' => 'ShoppingController@cartDelete',
    'as' => 'cart.delete'
]);

Route::post('/cart/add', [

    'uses' => 'ShoppingController@addToCart',
    'as' => 'cart.add'
]);

Route::get('/cart/checkout', [

    'uses' => 'CheckOutController@index',
    'as' => 'cart.checkout'
]);

Route::post('/shop/checkout', [

    'uses' => 'ShoppingController@cartCheckout',
    'as' => 'shop.checkout'
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function() {

    Route::get('/dashboard', [
        'uses' => 'AdminController@dashboard',
        'as' => 'admin.dashboard'
    ]);

    Route::resource('products', 'ProductsController');

    Route::resource('posts', 'PostController');

});

resources/views/admin/includes/errors.blade.php
@if(count($errors) > 0)
	
	<ul class="list-group">
		
		@foreach($errors->all() as $error)

			<li class="list-group-item text-danger">
				
				{{ $error }}

			</li>

		@endforeach

	</ul>

@endif

resources/views/admin/includes/head.blade.php
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{{ asset('admin/assets/img/logo-fav.png') }}">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/lib/material-design-icons/css/material-design-iconic-font.min.css') }}"/>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/lib/jqvmap/jqvmap.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/lib/datetimepicker/css/bootstrap-datetimepicker.min.css') }}"/>

    <link rel="stylesheet" type="text/css" href="{{ asset('admin/assets/lib/summernote/summernote-bs4.css') }}" />

    <link rel="stylesheet" href="{{ asset('admin/assets/css/app.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('admin/assets/css/custom.css') }}" type="text/css"/>

</head>

resources/views/admin/includes/nav.blade.php
<nav class="navbar navbar-expand fixed-top be-top-header">
    <div class="container-fluid">
        <div class="be-navbar-header">
            <a href="{{ route('admin.dashboard') }}" class="navbar-brand">Space Life Apparel</a>
        </div>
        <div class="be-right-navbar">
            <ul class="nav navbar-nav float-right be-user-nav">
                <li class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                        <img src="{{ asset('admin/assets/img/avatar.png') }}" alt="Username">
                        <span class="user-name">{{ auth()->user()->name }}</span></a>
                    <div role="menu" class="dropdown-menu">
                        <div class="user-info">
                            <div class="user-name">{{ auth()->user()->name }}</div>
                        </div>
                        <a href="{{route('logout')}}" class="dropdown-item"><span class="icon mdi mdi-power"></span> Logout</a>
                    </div>
                </li>
            </ul>
            <div class="page-title">
                <span>
                    @yield('pageTitle')
                </span>
            </div>
        </div>
    </div>
</nav>

resources/views/admin/includes/scripts.blade.php
<script src="{{ asset('admin/assets/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/js/app.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.pie.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.time.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/jquery.flot.resize.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/plugins/jquery.flot.orderBars.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/plugins/curvedLines.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-flot/plugins/jquery.flot.tooltip.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery.sparkline/jquery.sparkline.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/countup/countUp.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jqvmap/jquery.vmap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/jqvmap/maps/jquery.vmap.world.js') }}" type="text/javascript"></script>

<script src="{{ asset('admin/assets/lib/summernote/summernote-bs4.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('admin/assets/lib/summernote/summernote-ext-beagle.js') }}" type="text/javascript"></script>

resources/views/admin/includes/sidebar.blade.php
<div class="be-left-sidebar">
    <div class="left-sidebar-wrapper"><a href="#" class="left-sidebar-toggle">Dashboard</a>
        <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
                <div class="left-sidebar-content">
                    <ul class="sidebar-elements">
                        <li class="divider">Menu</li>
                        <li class="active">
                            <a href="{{ route('admin.dashboard') }}"><i class="icon mdi mdi-home"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="parent"><a href="#"><i class="icon mdi mdi-layers"></i><span>Products</span></a>
                            <ul class="sub-menu">
                                <li><a href="{{ route('products.create') }}">New Product</a>
                                </li>
                                <li><a href="{{ route('products.index') }}">All Products</a>
                                </li>
                            </ul>
                        </li>
                        <li class="parent"><a href="#"><i class="icon mdi mdi-layers"></i><span>Posts</span></a>
                            <ul class="sub-menu">
                                <li><a href="{{ route('posts.create') }}">New Post</a>
                                </li>
                                <li><a href="{{ route('posts.index') }}">All Posts</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/admin/includes/sucess.blade.php
@if(Session::has('success'))

    <div class="alert alert-success" role="alert" style="text-align: center;padding: 20px;font-size: 16px;">
        {{ Session::get('success') }}
    </div>

@endif